/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package airlinereservationsysytem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vibhanshu
 */
public class admin extends javax.swing.JInternalFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        autoid();
      
    }
     Connection con;
    PreparedStatement pre;
    public void autoid(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/vibhanshu?zeroDateTimeBehavior=CONVERT_TO_NULL","Vibhanshu","vib321@pa");
            pre=con.prepareStatement("select MAX(adminid) from admin");
            ResultSet rs=pre.executeQuery();
            rs.next();
            if(rs.getString("MAX(adminid)")==null){
//            if(rs.getString("MAX(id)"==null){
               userid.setText("AD001");
            }
            else{
                int id=Integer.parseInt(rs.getString("MAX(adminid)").substring(2,rs.getString("MAX(adminid)").length()));
                id++;
//                textid.setText("CS"tring.format("%03d",id));
                userid.setText("AD"+String.format("%03d",id));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ufname = new javax.swing.JTextField();
        cno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        userid = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(null);
        setClosable(true);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Admin (Add only authorized only)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 310, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Admin ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Contact Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        ufname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufnameActionPerformed(evt);
            }
        });
        getContentPane().add(ufname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, -1));
        getContentPane().add(cno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("User Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 151, -1));
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 151, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        userid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 51));
        userid.setText("userid");
        userid.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        getContentPane().add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 149, 22));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ufnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String AdminId=userid.getText();
          String FullName=ufname.getText();
        String UserName=uname.getText();
        String Contact=cno.getText();
        String Password=p.getText();
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/vibhanshu?zeroDateTimeBehavior=CONVERT_TO_NULL","Vibhanshu","vib321@pa");
            pre=con.prepareStatement("INSERT INTO admin(adminid, username, fullname, password,Contact) VALUES(?,?,?,?,?);");
            pre.setString(1,AdminId);
            pre.setString(2,UserName);
            pre.setString(3,FullName );
            pre.setString(4,Password);
            pre.setString(5,Contact );
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null    , "Succsessfully added");
            
            autoid();
       ufname.setText("");
       uname.setText("");
       cno.setText("");
       p.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField p;
    private javax.swing.JTextField ufname;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel userid;
    // End of variables declaration//GEN-END:variables
}
